#pragma once

#define MBEDTLS_AES_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_SHA256_C

#define MBEDTLS_CIPHER_MODE_CTR