#pragma once

#define VAR_NAME_MAX   13
#define AST_POOL_SIZE  256
#define VAR_MAX        32
#define FUNC_MAX       32
#define TOKEN_MAX      128

#define CALC_EXPR_LINE_LEN 74
#define CALC_EXPR_TOT_LEN (CALC_EXPR_LINE_LEN * 2)
#define CALC_NUM_CELLS 128
#define CALC_CELLS_PER_WINDOW 7

#define CALC_ERR_MSG_LEN 23
#define CALC_OUT_MSG_LEN 70

// Cell Flags
#define CALC_CELL_FLAG_EXISTS 0x01
#define CALC_CELL_FLAG_VALID 0x02
#define CALC_CELL_FLAG_OCCUPIED 0x04
#define CALC_CELL_FLAG_MODIFIED 0x08
